/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "text-primary": rgba(0, 0, 0, 0.87),
        "text-secondary": rgba(0, 0, 0, 0.6),
        "text-disabled": rgba(0, 0, 0, 0.38),
        primary: "#43A047",
        "primary-dark": "#2E7D32",
        "primary-light": "#66BB6A",
        "primary-contrast": "#FFFFFF",
        "primary-hover": rgba(56, 142, 60, 0.04),
        "primary-selected": rgba(56, 142, 60, 0.08),
        "primary-focus": rgba(56, 142, 60, 0.12),
        "primary-focus-visible": rgba(56, 142, 60, 0.3),
        "primary-outlined-border": rgba(56, 142, 60, 0.5),
        error: "#D32F2F",
        "error-dark": "#C62828",
        "error-light": "#EF5350",
        "error-contrast": "#FFFFFF",
        warning: "#EF6C00",
        "warning-dark": "#EF6C00",
        "warning-light": "#FF9800",
        "warning-contrast": "#FFFFFF",
        info: "#0288D1",
        "info-dark": "#01579B",
        "info-light": "#03A9F4",
        "info-contrast": "#FFFFFF",
        success: "#2E7D32",
        "success-dark": "#1B5E20",
        "success-light": "#4CAF50",
        "success-contrast": "#FFFFFF",
      },
    },
  },
  plugins: [],
};
